### ISSUE TITLE
Is this still available in Package Control?

### ISSUE THREAD

**Issue by SimonEast** [braver/MarkdownHighlighting#2]
I can see this package listed at https://packagecontrol.io/packages/MarkdownHighlighting but when I go to *Install New Package* in ST3, it's not listing it for me. Is it still published?

![screenshot - 26-feb-19 2_02_36 pm](https://user-images.githubusercontent.com/813734/53384519-4038f980-39cf-11e9-8297-99537fe89889.png)

**Comment by braver** [comment]
It's been removed. The package control website still lists packages after removal, but the tool in ST will not. It doesn't offer anything that the default Markdown package doesn't, and you can now easily extend color schemes to support the features you need: https://www.sublimetext.com/docs/3/color_schemes.html#customization
